apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-website
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: {{ .Values.ingress.path }}
          pathType: Prefix
          backend:
            service:
              name: nginx-website
              port:
                number: 80
