apiVersion: v1
kind: Service
metadata:
  name: nginx-website
spec:
  selector:
    app: nginx-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.service.type }}
